### ISSUE TITLE
第９回 11/20

### ISSUE THREAD

**Issue by katorie** [ikejirirb/metapro_ruby#10]
# 範囲！ 
* 第5章 

# すすめかた！
オンライン読書会で、1時間でできるところまで読んでみる！！ ➠ p113まで読んだ！

**Comment by katorie** [comment]
クラスは高性能なモジュール

**Comment by nappan23** [comment]
これを理解すればRubyの達人たちと自信を持って会話できる！

**Comment by risacan** [comment]
* 一番むずかしい
* クラスについて学んだことはモジュールについても適用できる
* Rubyのオブジェクトモデルの闇
* クラス定義でコードを実行している

**Comment by risacan** [comment]
* クラスもselfになれる
* カレントオブジェクト、カレントクラス
* instance_methodsででてくるメソッドの順番が2.5.0と2.5.1で変わる！

**Comment by risacan** [comment]
```
def add_method_to(klass)
  klass.class_eval do
    def m
      "#{self} ✨✨✨"
    end
  end
end

add_method_to String
puts "わーい".m
```

**Comment by katorie** [comment]
`exec` という単語を使うときの気持ちが知りたい

**Comment by risacan** [comment]
`bundle exec` とか `instance_exec` の `exec` ってどういうときに使うの...? いろんな意味がある便利な言葉なの...? 🤔

**Comment by risacan** [comment]
p112やばいから要復習！

**Comment by katorie** [comment]
113ページまで読んだ！
次回は　5.1.3　クラスインスタンス変数から！

**Comment by katorie** [comment]
> execute（エクセキュート）は要するにdoを丁寧にしたような単語で、日本語としては「実行する、遂行する」の意味になります。
しかし、ニュースで登場する多くは「死刑などを執行する」「殺す」を婉曲で表現したような意味になるので「（死刑などを）執行する」といった使い方になります。
死刑以外ではコンピューター、プログラミングの世界で登場することも多いですが、ごく普通の文章でも登場することがあるかもしれません。

https://talking-english.net/execute-execution/

**Comment by nappan23** [comment]
難しい
`class_eval` `class_exec` を使ったらどんな事ができるか書いてみる
